export const TestData = [
  {
    id: "1",
    logo: require("../assets/dapplogo/1inchexchange.png"),
    name: "1inch Exchange",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "2",
    logo: require("../assets/dapplogo/3kingdomsmultiverse.png"),
    name: "3 Kingdoms Multiverse",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "3",
    logo: require("../assets/dapplogo/3spaceart.png"),
    name: "3 Space Art",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "4",
    logo: require("../assets/dapplogo/a3stillalive.png"),
    name: "A3 Still Alive",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "5",
    logo: require("../assets/dapplogo/archeworld.png"),
    name: "ArcheWorld",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "6",
    logo: require("../assets/dapplogo/avatara.png"),
    name: "Avatara",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "7",
    logo: require("../assets/dapplogo/babylonsnftplatformlaunchpad.png"),
    name: "Babylon NFT Platform Launchpad",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "8",
    logo: require("../assets/dapplogo/basicincome.png"),
    name: "Basic Income",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "9",
    logo: require("../assets/dapplogo/beltfinance.png"),
    name: "Belt Finance",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "10",
    logo: require("../assets/dapplogo/bifi.png"),
    name: "BiFi",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "11",
    logo: require("../assets/dapplogo/bitgetswap.png"),
    name: "Bitget Swap",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "12",
    logo: require("../assets/dapplogo/claimswap.png"),
    name: "Claim Swap",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "13",
    logo: require("../assets/dapplogo/clubrare.png"),
    name: "Club Rare",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "14",
    logo: require("../assets/dapplogo/cpl.png"),
    name: "CPL",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "15",
    logo: require("../assets/dapplogo/defikingdoms.png"),
    name: "Defi Kingdoms",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "16",
    logo: require("../assets/dapplogo/definix.png"),
    name: "Definix",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "17",
    logo: require("../assets/dapplogo/dogesoundclub.png"),
    name: "Doge Sound Club",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "18",
    logo: require("../assets/dapplogo/drawshopkingdomreversedkr.png"),
    name: "Drawshop Kingdom Reversed KR",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "19",
    logo: require("../assets/dapplogo/eggverse.png"),
    name: "Eggverse",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "20",
    logo: require("../assets/dapplogo/fivestars.png"),
    name: "Five Stars",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "21",
    logo: require("../assets/dapplogo/gateio.png"),
    name: "Gate.io",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "22",
    logo: require("../assets/dapplogo/habl.png"),
    name: "Habl",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "23",
    logo: require("../assets/dapplogo/investar.png"),
    name: "Investar",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "24",
    logo: require("../assets/dapplogo/iskra.png"),
    name: "Iskra",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "25",
    logo: require("../assets/dapplogo/junmeta.png"),
    name: "JunMeta",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "26",
    logo: require("../assets/dapplogo/klaymeta.png"),
    name: "KlayMeta",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "27",
    logo: require("../assets/dapplogo/klayswap.png"),
    name: "KlaySwap",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "28",
    logo: require("../assets/dapplogo/klaytnnameservice.png"),
    name: "Klaytn Name Service",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "29",
    logo: require("../assets/dapplogo/klevaprotocol.png"),
    name: "Kleva Protocol",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "30",
    logo: require("../assets/dapplogo/metaworldmycity.png"),
    name: "MetaWorld My City",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "31",
    logo: require("../assets/dapplogo/mitagames.png"),
    name: "Mita Games",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "32",
    logo: require("../assets/dapplogo/neopin.png"),
    name: "NeoPin",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "33",
    logo: require("../assets/dapplogo/normainmetaland.png"),
    name: "Norma In Meta Land",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "34",
    logo: require("../assets/dapplogo/opensea.png"),
    name: "OpenSea",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "35",
    logo: require("../assets/dapplogo/orbitbridge.png"),
    name: "Orbit Bridge",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "36",
    logo: require("../assets/dapplogo/pala.png"),
    name: "Pala",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "37",
    logo: require("../assets/dapplogo/perfriendsl.png"),
    name: "PerFriends",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "38",
    logo: require("../assets/dapplogo/peterfarm.png"),
    name: "Peter Farm",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "39",
    logo: require("../assets/dapplogo/sheepfarminmetaland.png"),
    name: "Sheep Farm in Meta Land",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "40",
    logo: require("../assets/dapplogo/shoebillfinance.png"),
    name: "Shoebill Finance",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "41",
    logo: require("../assets/dapplogo/somesing.png"),
    name: "SomeSing",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "42",
    logo: require("../assets/dapplogo/spacefarm.png"),
    name: "Space Farm",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "43",
    logo: require("../assets/dapplogo/spellsofgenesis.png"),
    name: "Spells of Genesis",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "44",
    logo: require("../assets/dapplogo/superwalk.png"),
    name: "SuperWalk",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "45",
    logo: require("../assets/dapplogo/thekingoffightersarena.png"),
    name: "The King of Fighters Arena",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "46",
    logo: require("../assets/dapplogo/tofunft.png"),
    name: "Tofu NFT",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "47",
    logo: require("../assets/dapplogo/transitswap.png"),
    name: "Transit Swap",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "48",
    logo: require("../assets/dapplogo/xdao.png"),
    name: "XDAO",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "49",
    logo: require("../assets/dapplogo/xyfinance.png"),
    name: "XY Finance",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
];
