import logo from "../../assets/img/yourd-logo.png";

export const TestData = [
  {
    id: "1",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "2",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "3",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "4",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "5",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "6",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "7",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "8",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "9",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "10",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "11",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "12",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "13",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
  {
    id: "14",
    logo: "../../assets/img/yourd-logo.png",
    name: "YourD.yourd",
    category: ["NFT", "DeFi", "Klaytn", "contracts"],
    description: "did solution",
    link: "",
    path: "",
  },
];
